### ISSUE TITLE
Primary monitor

### ISSUE THREAD

**Issue by ochosi** [sj-p/xfce4-notifyd#1]
Hey, I think this is a great idea and in fact there is even a bugreport for the feature you worked on in bugzilla: https://bugzilla.xfce.org/show_bug.cgi?id=10003

However, the main developer/maintainer is mostly MIA, but I can review your patch later if you want. One more option I would like to propose (since we added support for this in xfce4-display-settings 4.12) is to always keep the notifications on the primary monitor (as set through RandR).
Thoughts?

**Comment by sj-p** [comment]
Hi, thanks for the interest. I'm aware of the bug report, in fact I had been planning to comment with a link to here, in case anyone affected wanted to try my version. But then a release date for 4.12 was announced & I held back, assuming there would be a feature freeze. And in the mean time, I moved on to other projects...

I agree it would good to use the primary monitor, where set, as the default. When time permits, I'll look into making this change.

**Comment by ochosi** [comment]
Actually xfce4-notifyd is not part of core, so a feature freeze wouldn't really apply to it anyway.

If you would get around to that, that'd be awesome!

**Comment by ochosi** [comment]
this has been added meanwhile as an option
